// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YukiChanR.Plugins.Arcaea;

#nullable disable

namespace YukiChanR.Plugins.Arcaea.Migrations
{
    [DbContext(typeof(ArcaeaDbContext))]
    [Migration("20230526123401_InitArcaeaDb")]
    partial class InitArcaeaDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YukiChanR.Plugins.Arcaea.Entities.ArcaeaDatabaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArcaeaCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arcaea_code");

                    b.Property<string>("ArcaeaName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arcaea_name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("arcaea_users");
                });

            modelBuilder.Entity("YukiChanR.Plugins.Arcaea.Entities.ArcaeaUserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Best30ShowGrade")
                        .HasColumnType("boolean")
                        .HasColumnName("b30_show_grade");

                    b.Property<bool>("Dark")
                        .HasColumnType("boolean")
                        .HasColumnName("dark");

                    b.Property<bool>("Nya")
                        .HasColumnType("boolean")
                        .HasColumnName("nya");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<bool>("SingleDynamicBackground")
                        .HasColumnType("boolean")
                        .HasColumnName("single_dynamic_bg");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("arcaea_preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
