name: Build and Push Docker Images

on:
  push:
    tags: [ v*.*.* ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: bsdayo
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Inspect Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: bsdayo/yukichan-r
          tags: |
            type=semver,pattern={{version}}
            type=match,pattern=(?<=v\d\.\d\.\d-)[a-z]+(?=\.?)

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
