name: Auto Release

on:
  push:
    tags: [ v*.*.* ]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch remote tags
        run: git fetch --prune --tags

      - name: Generate release note
        run: |
          echo -e "> 暂时还没有说明哦...\n" >> release-note

          previousTag=$((git tag -l | grep -B1 $GITHUB_REF_NAME | grep -v $GITHUB_REF_NAME) || echo '')
          comparePath=$([ -z $previousTag ] && echo -e "commits/$GITHUB_REF_NAME" || echo -e "compare/$previousTag...$GITHUB_REF_NAME")
          echo -e "**Full Changelog**: https://github.com/$GITHUB_REPOSITORY/$comparePath" >> release-note

      - name: Preview release note
        run: cat release-note

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release-note
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
