name: Tag commit

on:
  push:
    branches: [dev]

jobs:
  tag-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag commit
        run: |
          version=$(cat src/YukiChanR/YukiChanR.csproj | grep -Po "(?<=\<Version\>).*(?=\</Version\>)")

          if [ ! $(git tag | awk "\$1 == \"v$version\" { print \$1 }") ]; then
              echo "Tagging $version to $GITHUB_SHA..."
              git config user.name $GITHUB_ACTOR
              git config user.email ${GITHUB_ACTOR}@users.noreply.github.com
              git tag "v$version"
              git push origin "v$version"
          fi
