name: Tag commit

on:
  push:
    branches: [dev]

jobs:
  tag-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tag commit
        run: |
          version=$(cat src/YukiChanR/YukiChanR.csproj | grep -Po "(?<=\<Version\>).*(?=\</Version\>)")
          echo $version
          if [ $(git tag | awk "\$1 == \"v$version\" { print \$1 }") ]; then
              git config user.name $GITHUB_ACTOR
              git config user.email ${GITHUB_ACTOR}@users.noreply.github.com
              git tag $version
              git push origin $version
          fi
